spring.application.name=SendService

#Configuration of the port number
server.port = 0


#Configuration of the Kafka Producer
spring.kafka.producer.bootstrap-servers = localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer


#Make sure producer is idempotent enabling idempotency should use acknowledgement to be all
spring.kafka.producer.properties.enable.idempotency=true
spring.kafka.producer.acks=all

#Kafka retries
spring.kafka.producer.retries=10
spring.kafka.producer.retry.backoff.ms=1000

